Add logging helpers for `Dumpable` and `Yamlizable`
revng/revng pull request #145
Opened 2022-03-07 16:14 UTC by AlviseDeFaveri

2022-03-07 16:18 UTC, AlviseDeFaveri commented
Note: this PR has a twin MR in `revng-c`

2022-03-10 16:32 UTC, aleclearmind requested changes

2022-03-10 16:32 UTC, aleclearmind commented on include/revng/Support/IRHelpers.h
> +    P.dump(Stream);
I usually do like this in order to be sure that the stream is flushed, but it's probably not necessary.
```suggestion
    {
      llvm::raw_svector_ostream Stream(Buffer);
      P.dump(Stream);
    }
```

2022-03-16 15:00 UTC, aleclearmind commented on include/revng/Support/YAMLTraits.h
> +}
Your `serializeToString` could reuse the `serialize` function.
If you do so, the version taking `const T` can call the corresponding `serialize` function and we have one less `const_cast` in our codebase, which is good.

2022-03-16 15:44 UTC, AlviseDeFaveri commented on include/revng/Support/YAMLTraits.h
> +}
keeping only the `const` version only and using `serialize()` in it appears to work smoothly, not sure it's the right way to do it though

2022-03-18 12:13 UTC, aleclearmind commented
Merged in 16b7c61. Thanks!

2022-03-18 12:13 UTC, closed without merging