Add `StringMapContainer`
revng/revng pull request #165
Opened 2022-04-19 11:16 UTC by pfez

The container maps a `MetaAddress` to an arbitrary string

2022-04-19 21:00 UTC, aleclearmind requested changes

2022-04-20 13:33 UTC, pfez commented on lib/Pipes/StringMapContainer.cpp
> +}
I totally forgot about this. Should be good now.

2022-04-20 13:33 UTC, pfez commented on lib/Pipes/StringMapContainer.cpp
> +  for (const auto &[MetaAddr, Mapped] : Map)
Done

2022-04-20 13:33 UTC, pfez commented on lib/Pipes/StringMapContainer.cpp
> +    std::string MetaAddrStr = T.getPathComponents().back().getName();
Done

2022-04-21 13:22 UTC, merged