Expose invalidations in GraphQL & MIME Fixes
revng/revng pull request #226
Opened 2022-10-03 15:36 UTC by mrjackv

2022-10-04 12:13 UTC, aleclearmind commented
The branch name doesn't seem appropriate.

2022-10-04 12:23 UTC, aleclearmind commented
Yes, branch names are important.

2022-10-05 15:58 UTC, mrjackv commented
Split the PR, since the changes where uncorrelated
This is for some fixes to the PTML output and the new MIME convention

2022-10-06 08:26 UTC, aleclearmind requested changes

2022-10-06 09:50 UTC, mrjackv commented on include/revng/Pipes/Ranks.h
> +using UFK = model::UnionField::Key;
Done

2022-10-06 09:53 UTC, mrjackv commented on include/revng/Yield/Pipes/YieldControlFlow.h
> +inline constexpr char FunctionAssemblyPTMLMIMEType[] = "text/x.asm+ptml+yaml";
Appended section about MIME types in the PTML pad

2022-10-12 09:53 UTC, aleclearmind commented
Merged in 025f6d5. Thanks!

2022-10-12 09:53 UTC, closed without merging