Changes for revng-distributable-revamp
revng/revng pull request #239
Opened 2022-10-26 15:18 UTC by mrjackv

2022-10-28 14:51 UTC, aleclearmind requested changes

2022-10-28 14:51 UTC, aleclearmind commented on python/revng/cli/_commands/daemon_self_test.py
> +            self.log(f"\n\nDaemon Stacktrace:\n{stdout}")
`"\n\nrevng-daemon output:\n`

2022-10-28 14:51 UTC, aleclearmind commented on lib/Support/PathList.cpp
> +    llvm::StringRef File = Parts[5].ltrim();
Mmmh, this does not fix the problem described in the commit message.
You should get anything that comes after the 4th space.

2022-10-28 15:01 UTC, aleclearmind commented on lib/Support/PathList.cpp
> +    llvm::StringRef File = Parts[5].ltrim();
Ah-ah! Didn't know that! My bad!

2022-10-28 15:30 UTC, mrjackv commented on python/revng/cli/_commands/daemon_self_test.py
> +            self.log(f"\n\nDaemon Stacktrace:\n{stdout}")
Fixed

2022-11-07 07:53 UTC, aleclearmind commented
Merged in 91c4bdc. Thanks!

2022-11-07 07:53 UTC, closed without merging