Add RecursiveCoroutine headers and tests
revng/revng pull request #29
Opened 2020-12-16 09:24 UTC by pfez

RecursiveCoroutines are a facility intended to be used as-drop in replacement of recursive functions.

They provide the following features.
- They can be written almost as regular recursive functions, with 4 caveats.
  1. A recursive coroutine that returns a type `T`, needs to be declared to return a `RecursiveCoroutine<T>`.
  2. Inside the body of a recursive coroutine, when recursively calling another recursive coroutine, the recursive call needs to be prepended by the new keywork `rc_recur`.
  3. Inside the body of a recursive coroutine, the `return` statement needs to be substituted with `rc_return`.
  4. When launching a recursive coroutine `A` from a function that is not a recursive coroutine, `A` needs to be called with the provided dedicated template wrapper `rc_run`. The syntax is the following `rc_run(A, arg0, arg1, ...)`. This is necessary to enable swapping off recursive coroutine and fall back to regular recursion for debug. See below for how to do it.
- Unlike regular recursive functions, they don't use the system stack for recursion. They use a custom heap-allocated stack to manage recursion. This makes them more robust for implementing recursive functions that manipulate user-defined input, because they are much less likely to trigger stack overflow.
- They can be turned off compiling with `-DDISABLE_RECURSIVE_COROUTINES`, falling back to regular recursion, for debug purposes.
- They support both direct and indirect recursion, i.e. a recursive coroutine A can recursively call itself, or it can recursively call another recursive coroutine B, which in turns recursively calls A.

2020-12-16 13:08 UTC, aleclearmind requested changes

2020-12-16 13:08 UTC, aleclearmind commented on include/revng/ADT/RecursiveCoroutine-coroutine.h
> +
License notice?

2020-12-16 13:08 UTC, aleclearmind commented on tests/unit/recur.cpp
> +  printf("Average: %lld\n", Average);
Let's drop `printf`s

2020-12-16 17:09 UTC, pfez commented on include/revng/ADT/RecursiveCoroutine-coroutine.h
> +
Added to all the files!

2020-12-16 17:20 UTC, pfez commented on tests/unit/recur.cpp
> +  printf("Average: %lld\n", Average);
Done this as well.

2020-12-16 17:21 UTC, pfez commented
If you have no other comments this should be good to go now!

2020-12-29 14:58 UTC, aleclearmind commented on tests/unit/UnitTests.cmake
> +set_target_properties(test_recursive_coroutines_fallback PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -DDISABLE_RECURSIVE_COROUTINES" )
`${COMPILE_FLAGS}` doesn't do what you think here.

2020-12-29 14:58 UTC, aleclearmind commented on tests/unit/UnitTests.cmake
> +set_target_properties(test_recursive_coroutines_iterative PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} -DITERATIVE" )
Very redundant, I'm factoring it out in a macro

2020-12-29 14:58 UTC, aleclearmind commented on tests/unit/UnitTests.cmake
> +revng_add_private_executable(test_recursive_coroutines "${SRC}/recur.cpp")
`recur.cpp` was a temporary name. I'm renaming it to `RecursiveCoroutine.cpp`.

2020-12-29 14:59 UTC, aleclearmind commented
I'm taking ownership of this PR, no further changes required from your side.

2020-12-29 19:12 UTC, aleclearmind commented
Merged in e1b283b0b682877fcb6a8a215022520479d005ec. Thanks!

2020-12-29 19:12 UTC, closed without merging